# Practice with Joins
----------------------

In [45]:
# https://drive.google.com/file/d/1QN19jrN6Tc2IeXyrrTvyAdWU4hs97Hj5/view?usp=sharing
!gdown 1QN19jrN6Tc2IeXyrrTvyAdWU4hs97Hj5

Downloading...
From: https://drive.google.com/uc?id=1QN19jrN6Tc2IeXyrrTvyAdWU4hs97Hj5
To: /content/median-home-value-town-2018.csv
100% 478k/478k [00:00<00:00, 128MB/s]

In [46]:
import pandas as pd
df_h = pd.read_csv('/content/median-home-value-town-2018.csv')

In [47]:
df_h.head()

,Town,FIPS,Year,Measure Type,Variable,Value
0,Andover,901301080,2006-2010,Number,Median Home Value,276300.00
1,Andover,901301080,2006-2010,Number,Margins of Error,21727.00
2,Andover,901301080,2006-2010,Ratio to State Median,Median Home Value,0.93
3,Andover,901301080,2006-2010,Ratio to State Median,Margins of Error,0.07
4,Andover,901301080,2007-2011,Number,Median Home Value,303500.00

In [48]:
# prompt: reshape this dataframe so that 'Variable' and 'Measure Type' are the columns, and it is filled with Value by Town and Year

df_h_reshaped = df_h.pivot_table(values='Value',
                                 index=['Town', 'Year'],
                                 columns=['Variable','Measure Type'])
df_h_reshaped.head()

Variable          Margins of Error                       Median Home Value  \
Measure Type                Number Ratio to State Median            Number
Town    Year
Andover 2006-2010          21727.0                  0.07          276300.0
        2007-2011          27437.0                  0.09          303500.0
        2008-2012          29645.0                  0.10          302500.0
        2009-2013          35510.0                  0.13          287200.0
        2010-2014          24078.0                  0.09          303200.0

Variable
Measure Type      Ratio to State Median
Town    Year
Andover 2006-2010                  0.93
        2007-2011                  1.04
        2008-2012                  1.06
        2009-2013                  1.03
        2010-2014                  1.10

In [49]:
# flatten the index
df_h_reshaped.reset_index(inplace=True)
df_h_reshaped.head()

Variable         Town       Year Margins of Error                        \
Measure Type                               Number Ratio to State Median
0             Andover  2006-2010          21727.0                  0.07
1             Andover  2007-2011          27437.0                  0.09
2             Andover  2008-2012          29645.0                  0.10
3             Andover  2009-2013          35510.0                  0.13
4             Andover  2010-2014          24078.0                  0.09

Variable     Median Home Value
Measure Type            Number Ratio to State Median
0                     276300.0                  0.93
1                     303500.0                  1.04
2                     302500.0                  1.06
3                     287200.0                  1.03
4                     303200.0                  1.10

In [50]:
# https://drive.google.com/file/d/1b6FCberp37AH_z01p2PNznRjoiLn-V3Y/view?usp=sharing
!gdown 1b6FCberp37AH_z01p2PNznRjoiLn-V3Y

Downloading...
From: https://drive.google.com/uc?id=1b6FCberp37AH_z01p2PNznRjoiLn-V3Y
To: /content/poverty-status-by-town-2018.csv
100% 30.6M/30.6M [00:00<00:00, 203MB/s]

In [51]:
df_p = pd.read_csv('/content/poverty-status-by-town-2018.csv')
df_p.head()

,Town,FIPS,Year,Race/Ethnicity,Age,Poverty Status,Measure Type,Variable,Value
0,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Number,Margins of Error,49.00
1,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Number,Poverty Status,80.00
2,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Percent,Poverty Status,2.46
3,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Percent,Margins of Error,1.51
4,Andover,901301080,2005-2009,All,Total,Poverty Status Determined,Number,Poverty Status,3248.00

In [52]:
df_p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238000 entries, 0 to 237999
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   Town            238000 non-null  object
 1   FIPS            238000 non-null  int64
 2   Year            238000 non-null  object
 3   Race/Ethnicity  238000 non-null  object
 4   Age             238000 non-null  object
 5   Poverty Status  238000 non-null  object
 6   Measure Type    238000 non-null  object
 7   Variable        238000 non-null  object
 8   Value           238000 non-null  float64
dtypes: float64(1), int64(1), object(7)
memory usage: 16.3+ MB

In [53]:
df_p['Race/Ethnicity'].value_counts()

All                                           23800
American Indian and Alaska Native Alone       23800
Asian Alone                                   23800
Black or African American Alone               23800
Hispanic or Latino                            23800
Native Hawaiian and Other Pacific Islander    23800
Some Other Race Alone                         23800
Two or More Races                             23800
White Alone                                   23800
White Alone Not Hispanic or Latino            23800
Name: Race/Ethnicity, dtype: int64

In [54]:
df_p = df_p[df_p['Race/Ethnicity']=='All']
df_p.shape

(23800, 9)

In [55]:
df_p['Poverty Status'].value_counts()

Below Poverty Level          13600
Poverty Status Determined    10200
Name: Poverty Status, dtype: int64

In [56]:
df_p.head()

,Town,FIPS,Year,Race/Ethnicity,Age,Poverty Status,Measure Type,Variable,Value
0,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Number,Margins of Error,49.00
1,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Number,Poverty Status,80.00
2,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Percent,Poverty Status,2.46
3,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Percent,Margins of Error,1.51
4,Andover,901301080,2005-2009,All,Total,Poverty Status Determined,Number,Poverty Status,3248.00

In [57]:
df_p = df_p[df_p['Variable']=='Poverty Status']
df_p = df_p[df_p['Measure Type']=='Percent']
df_p.head()

,Town,FIPS,Year,Race/Ethnicity,Age,Poverty Status,Measure Type,Variable,Value
2,Andover,901301080,2005-2009,All,Total,Below Poverty Level,Percent,Poverty Status,2.46
8,Andover,901301080,2005-2009,All,Under 18,Below Poverty Level,Percent,Poverty Status,0.00
12,Andover,901301080,2005-2009,All,Under 18,Poverty Status Determined,Percent,Poverty Status,22.66
143,Andover,901301080,2006-2010,All,Total,Below Poverty Level,Percent,Poverty Status,4.68
149,Andover,901301080,2006-2010,All,Under 18,Below Poverty Level,Percent,Poverty Status,0.00

In [58]:
df_p_reshaped = df_p.pivot_table(values='Value',
                                 index=['Town', 'Year'],
                                 columns=['Age', 'Poverty Status'])
df_p_reshaped.head()

Age                             Total            Under 18  \
Poverty Status    Below Poverty Level Below Poverty Level
Town    Year
Andover 2005-2009                2.46                0.00
        2006-2010                4.68                0.00
        2007-2011                5.71                8.19
        2008-2012                4.94                7.48
        2009-2013                4.33                7.43

Age
Poverty Status    Poverty Status Determined
Town    Year
Andover 2005-2009                     22.66
        2006-2010                     22.56
        2007-2011                     23.90
        2008-2012                     23.71
        2009-2013                     24.36

In [59]:
df_p_reshaped.reset_index(inplace=True)
df_p_reshaped.head()

Age                Town       Year               Total            Under 18  \
Poverty Status                     Below Poverty Level Below Poverty Level
0               Andover  2005-2009                2.46                0.00
1               Andover  2006-2010                4.68                0.00
2               Andover  2007-2011                5.71                8.19
3               Andover  2008-2012                4.94                7.48
4               Andover  2009-2013                4.33                7.43

Age
Poverty Status Poverty Status Determined
0                                  22.66
1                                  22.56
2                                  23.90
3                                  23.71
4                                  24.36

In [60]:
df_p_reshaped.columns

MultiIndex([(    'Town',                          ''),
            (    'Year',                          ''),
            (   'Total',       'Below Poverty Level'),
            ('Under 18',       'Below Poverty Level'),
            ('Under 18', 'Poverty Status Determined')],
           names=['Age', 'Poverty Status'])

In [61]:
# prompt: Using dataframe df_h_reshaped: flatten the multi-index for the columns into one string

df_h_reshaped.columns = ["_".join(x) for x in df_h_reshaped.columns.ravel()]
df_p_reshaped.columns = ["_".join(x) for x in df_p_reshaped.columns.ravel()]

<ipython-input-61-355df265f657>:3: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  df_h_reshaped.columns = ["_".join(x) for x in df_h_reshaped.columns.ravel()]
<ipython-input-61-355df265f657>:4: FutureWarning: Index.ravel returning ndarray is deprecated; in a future version this will return a view on self.
  df_p_reshaped.columns = ["_".join(x) for x in df_p_reshaped.columns.ravel()]

In [62]:
df_h_reshaped.columns

Index(['Town_', 'Year_', 'Margins of Error_Number',
       'Margins of Error_Ratio to State Median', 'Median Home Value_Number',
       'Median Home Value_Ratio to State Median'],
      dtype='object')

In [63]:
df_h_reshaped.shape

(1530, 6)

In [64]:
df_h_reshaped.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 6 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Town_                                    1530 non-null   object
 1   Year_                                    1530 non-null   object
 2   Margins of Error_Number                  1530 non-null   float64
 3   Margins of Error_Ratio to State Median   1530 non-null   float64
 4   Median Home Value_Number                 1530 non-null   float64
 5   Median Home Value_Ratio to State Median  1530 non-null   float64
dtypes: float64(4), object(2)
memory usage: 71.8+ KB

In [65]:
df_p_reshaped.columns

Index(['Town_', 'Year_', 'Total_Below Poverty Level',
       'Under 18_Below Poverty Level', 'Under 18_Poverty Status Determined'],
      dtype='object')

In [66]:
df_p_reshaped.shape

(1700, 5)

In [70]:
import pandas as pd
new_df = pd.merge(left=df_h_reshaped,
                  right=df_p_reshaped,
                  left_on=['Town_', "Year_"],
                  right_on=['Town_', "Year_"],
                            how='left')
print(new_df.shape)

(1530, 9)

In [71]:
new_df

,Town_,Year_,Margins of Error_Number,Margins of Error_Ratio to State Median,Median Home Value_Number,Median Home Value_Ratio to State Median,Total_Below Poverty Level,Under 18_Below Poverty Level,Under 18_Poverty Status Determined
0,Andover,2006-2010,21727.0,0.07,276300.0,0.93,4.68,0.00,22.56
1,Andover,2007-2011,27437.0,0.09,303500.0,1.04,5.71,8.19,23.90
2,Andover,2008-2012,29645.0,0.10,302500.0,1.06,4.94,7.48,23.71
3,Andover,2009-2013,35510.0,0.13,287200.0,1.03,4.33,7.43,24.36
4,Andover,2010-2014,24078.0,0.09,303200.0,1.10,3.68,6.86,23.36
...,...,...,...,...,...,...,...,...,...
1525,Woodstock,2010-2014,25358.0,0.09,246200.0,0.90,2.31,1.86,23.74
1526,Woodstock,2011-2015,13658.0,0.05,242500.0,0.90,3.35,3.68,21.39
1527,Woodstock,2012-2016,15077.0,0.06,246600.0,0.92,2.91,2.97,19.29
1528,Woodstock,2013-2017,14279.0,0.05,247500.0,0.92,5.95,9.11,20.33
1529,Woodstock,2014-2018,14750.0,0.05,256800.0,0.94,4.44,6.86,21.26